### ISSUE TITLE
Comments reposted multiple times?

### ISSUE THREAD

**Issue by SpookyAction** [blogs-perl-org/blogs.perl.org#121]
Not sure if this has been filed already, but I noticed on several blog posts comments were being reposted multiple times. It seems to happen to commenters  logged in through OpenID.

http://blogs.perl.org/users/mike_friedman/2011/04/heres-a-stupid-bug.html

http://blogs.perl.org/users/shlomi_fish/2011/04/introduction-to-blogsperlorg-texttable.html

**Comment by ap** [comment]
> It seems to happen to commenters logged in through OpenID.

This makes it likely [a case of what was outlined](/blogs-perl-org/blogs.perl.org/issues/119#issuecomment-1074905) by @kentfredric in #119.

I haven’t seen this happen in a very long time, even though I’m pretty sure this bug is still present. I believe its relevance has become theoretical since b.p.o only supports legacy OpenID, which is largely dead – basically my theory is that people no longer use the functionality which would still have this problem.

Nor are they going to in the future, since no form of “Log in with X” is coming back under MT. If it comes back it will be under a different CMS – which will not have the same constellation of circumstances which causes this problem under MT.
