### ISSUE TITLE
sophia_wright is a spammer

### ISSUE THREAD

**Issue by book** [blogs-perl-org/blogs.perl.org#253]
http://blogs.perl.org/users/sophia_wright/

**Comment by ap** [comment]
> Maybe a good way to hide spammers from sight would be to not include in the main page any post from users that created an accound less than 24 or 48 hours ago. And also automatically open a "potential spammer" issue for users that post within hours of their account creation.

@book Funny, this is roughly what ended up getting implemented, some of it soon after and some of it years later. New users are barred from the front page and RSS feed (although not on a time-limited basis – they are born into purgatory and stay there until manually released), and there is a trigger on the first post from each user (again regardless of how long ago they registered, and it is sent via email instead of an issue). This is why front page spam ended 2½ years ago.
