### ISSUE TITLE
Enable HTTPS for blogs.perl.org

### ISSUE THREAD

**Issue by briandfoy** [blogs-perl-org/blogs.perl.org#254]
I'd like to use HTTPS everywhere so man in the middle problems like http://blogs.perl.org/users/ivan_bessarabov/2014/02/blogsperlorg-and-https.html don't happen.

**Comment by joshrabinowitz** [comment]
It's 2019! Seems like this should get implemented?

In particular, the login page is not https protected. Also letsencrypt makes this less expensive and perhaps easier to setup than it was in previous years.

**Comment by davorg** [comment]
I agree with all of this. Particularly as browsers have started to warn on passwords on pages that are served over HTTP.

It seems that we have spent most of the last four or five years expecting this site to be moved to new technology on new hosting imminently. I still think that's relatively imminent, but I'll spend some time over the next couple of weeks looking at what we need to do in order to implement this.

**Comment by tobyink** [comment]
Any progress on this? Adding HTTPS support for a site isn't usually more than an hour's work.

**Comment by jberger** [comment]
I agree with @tobyink, I could even do the work: https://dev.to/joelaberger/no-magic-letsencrypt-certbot-and-nginx-configuration-recipe-3a97

**Comment by benkasminbullock** [comment]
Can the site maintainers please respond to the queries here?

**Comment by jberger** [comment]
> Can the site maintainers please respond to the queries here?

At this point I assume no effort is being put into the site. As a result, sadly I've decided that it won't be worth my effort to put content here if browsers will be blocking it.

**Comment by ap** [comment]
The answer is basically “if you want to go there I would not start from here”. HTTPS support isn’t a lot of work to add – provided you are in a place from which it’s not a lot of work to add. The site is on a very old OS with crypto libraries so old it’s impossible to even connect to Let’s Encrypt, let alone obtain a certificate. I’ve checked. If that had been all that was necessary, I’d’ve done it a long time ago. Alas.

There is a bit of rabbit hole there. The site is on an expensive hosting plan, renting hardware that was high-end back when the site was set up. Moving the site is not an obvious endeavour because the way MT was deployed is basically “extract a tarball and fiddle around with it on the machine” and MT is a CGI-era design that doesn’t particularly separate user data from application code – everything just goes in the same tree and you have to know which parts are what. There are, at least, etckeeper records for the contents of `/etc`, but traceability is scarce aside from that.

That said, I’m shaving all the yaks. (Not least because I want to stop paying so absurdly much to keep the lights on! But when my bill goes down it’ll also mean SSL will be easy to enable.) It’s just a lower priority than my job and life in general (which have gone about as well as everyone else’s last year) – so yes, outward progress is slow.

(It doesn’t help that the progress I *have* made is going to make even less visible that anything is going on. Namely there are now countermeasures that finally make it impossible for spam to hit the front page. You might note that the spam reports filed in this issue tracker stopped dead a while ago. That’s where most of my energy went before.)

My ultimate goal too is not to just to move the site but to also make the setup repeatable and to have notes on all of it, which makes things slower than they could be. The upside is that ongoing effort should drop as I get everything where I want it to be, but to get there I have to dig my way a fair way to the surface.

(FWIW my two big visible goals are SSL and fixing the “session lost” bug when submitting from the comment preview screen.)

**Comment by jberger** [comment]
> That said, I’m shaving all the yaks. [snip] so yes, outward progress is slow.

Honestly I'm just glad to see that anyone is working on it at all

**Comment by Grinnz** [comment]
Would one possibility for quick SSL be to have SSL termination on a separate device or service? (The NOC may even be able to help with this) That depends on whether there's a way to set this up without exposing the machine without SSL on the public internet, though it's not like that would be worse than the current situation anyway.

**Comment by jberger** [comment]
In addition to NOC, Cloudflare offers free ssl/proxy for open source projects. Both mojo and convos use it. That could also be an easy way to handle ssl in your case.

**Comment by jberger** [comment]
(Downvoting without comment is infuriating)

**Comment by ap** [comment]
@Grinnz

> Would one possibility for quick SSL be to have SSL termination on a separate device or service?

It might – I’ve considered setting up the new hosting and proxying from it to the old server. It’s just that if that situation is going to persist for a while, it means I need to pay even more in the meantime. (And if that situation isn’t going to persist for very long? Then why go to the trouble.)

Cloudflare is an answer there. I’m just too much of an ideologue to feel comfortable handing them all “my” visitors on a platter. (My very first action as newly sole operator was to throw out Google Analytics…) So it’ll have to go the slower way.

I did also briefly look into other options like a proxy in a static-linked binary, so I could get something with contemporary crypto onto the machine without trying to update all of it. But I didn’t get anywhere within the amount of effort I was willing to expend on this.

But this issue is what I’m working on now when I’m working on b.p.o.

**Comment by benkasminbullock** [comment]
What kind of help can we offer you @ap? Do you want money to help with the server costs, or do you want volunteers to help with the coding or the system/webserver administration work?

**Comment by nrdvana** [comment]
IMO the most pragmatic way to make the problem go away is to make a tarball of the whole server, make that into a Docker image, and install that and traefik on a Linode for $10/mo.  Turn on LetsEncrypt options in traefik for permanent free ssl.

The most effort would be in fixing the init scripts to start your services under docker.  Though you won’t need most of the services anymore, so just hack something together based on what needs to be running.  (apache & mysql?) This also assumes the host is Linux, where you can often combine a new kernel with ancient userspace with no problem.

**Comment by nrdvana** [comment]
I have since learned that traefik is itself a static binary with no dependencies!  so it should run on any host with a compatible kernel.  I wrote up config files for you to save the trouble of digging through traefik's many options:

  *  http://blogs.perl.org/users/nerdvana/2021/11/ssl-is-easy-with-traefik.html

**Comment by ap** [comment]
> it should run on any host with a compatible kernel

It does!

> I wrote up config files for you to save the trouble of digging through traefik's many options:

Thanks! I’ve not gone through and set every thing up properly just yet but I did take a hacksaw to your examples and manage to reconstitute them into a minimal example to verify that Traefik can indeed serve the site over up-to-date TLS from the aging machine blogs.perl.org is still hosted on.

I can’t take the time to do more than that right now but I’ll be getting to it very soon.

Much appreciated!

**Comment by xkcd386at** [comment]
you might also consider caddy (caddyserver.com).  With caddy, a simple reverse proxy is as easy as `caddy reverse-proxy --from example.com --to localhost:9000`.  See https://caddyserver.com/docs/quick-starts/https#the-reverse-proxy-command and other parts of caddy's documentation for more.

I'm not affiliated with caddy in any way except I love the product.

(Everything else is same as traefic -- single static binary that should run anywhere, manages lets-encrypt interaction, etc)

**Comment by bessarabov** [comment]
🎉 

It looks like https://blogs.perl.org/ is working via https now!

![Screen Shot 2022-09-25 at 08 44 45](https://user-images.githubusercontent.com/47263/192130207-dac919bb-d745-4a54-9ca9-43a875c29887.png)

![Screen Shot 2022-09-25 at 08 46 17](https://user-images.githubusercontent.com/47263/192130223-5601e5d6-9bb1-4ccb-a4cc-17c696071a93.png)


(but the link "Sign in" redirects to http page)

**Comment by joshrabinowitz** [comment]
I noticed also that it seems the login page _supports_ https, it looks like the link to login (and many others) still specify non-encrypted http.

**Comment by ap** [comment]
Yes, that has been deployed for a long time. It’s the easy bit in the “HTTPS is easy” slogan.

Unfortunately the easy bit is not enough. MovableType generates absolute links in various contexts but not in others, particularly in the logged in backend, so even if you start out with a HTTPS URL, this won’t necessarily stick.

I last looked at the whole issue long enough ago that I’ve forgotten the details, but it was not trivial to fix. Every single blog on b.p.o has its own copy of the CSS etc which makes it more complicated to fix; centralizing them to all use a single copy would make this easier. Dealing with MT’s incurable absolute link compulsion will require a plugin. Templates will need editing to make use of that plugin. Version control of the templates hasn’t been done cleanly in a while and I wanted to properly commit the changes so far first. Etc. It’s all doable, it just involves enough yak shaving that I had to put it on the back burner, and that’s where it’s been sitting ever since. I’ll need a chunk of time off from work to get through this. Hopefully soon.

**Comment by haarg** [comment]
https doesn't seem to be working at all anymore.

**Comment by ap** [comment]
I turned it off for now. It is unfinished, so I never released it for public consumption, but it was easy to find anyway, so people kept doing so and then expecting it to work. For whatever reason (maybe none at all) the tempo of that has picked up recently, and since #415 I’ve been getting the same complaint daily in various places.

**Comment by ap** [comment]
I turned it off for now. It is unfinished, so I never released it for public consumption, but it was easy to find anyway, so people kept doing so and then expecting it to work. For whatever reason (maybe none at all) the tempo of that has picked up recently, and since #415 I’ve been getting the same complaint on the daily in various places.

**Comment by joshrabinowitz** [comment]
I understand the difficulty (as described), but getting this done will only rise in importance and awareness.Maybe some sort of multi-person hackathon?

**Comment by ap** [comment]
I’ll have time off soon and I’m coming around to “fuck it, we'll do it live” (i.e. with parts of the site being broken temporarily (as opposed to the stepwise transition I had in mind before, which would have happened basically invisibly)). I would far prefer to get it done without disruptions, but evidently the price for that is further interminable delays, and in retrospect I should have cut my losses a while ago.

**Comment by nrdvana** [comment]
I haven't used this myself, but Traefik also has a [3rd party plugin for rewriting served pages](https://github.com/traefik/plugin-rewritebody) which you could use to globally rewrite http: to https: for the absolute URLs.  that would make it a one-stop solution instead of crawling through the MovableType implementation to find where they get generated.

I'm sure that apache also has a solution for this, but I can't seem to find it.  Maybe it was only mod_proxy that I'm thinking of, which only affects pages served from a back-end with apache as the proxy.

**Comment by ap** [comment]
Good point. I used Caddy and it has [an equivalent module](https://github.com/caddyserver/replace-response). I’ll look into this.

**Comment by ap** [comment]
Well whaddayaknow.

**Comment by ap** [comment]
I left this ticket open in case any gremlins popped up, but it looks like there aren’t any obvious ones. So I guess we’re done here, folks, and you can all return home. Thanks for coming out.
