### ISSUE TITLE
blogs.perl.org is not mobile friendly

### ISSUE THREAD

**Issue by mperry2** [blogs-perl-org/blogs.perl.org#298]
blogs.perl.org isn't very usable or readable on mobile devices such as phones. The text is so small as to be impossible to read without zooming and scrolling left and right. A third of the width of the screen is taken up by blank space due to the search and "about" boxes.

**Comment by ap** [comment]
You have a point… but given the mass of longstanding unresolved dowright-existential bugs we are struggling with, expect this to be a low priority indeed, out to the indefinite. Sorry.

**Comment by benkasminbullock** [comment]
It's a relatively simple matter to do things like adding a viewport to the HTML template which would solve quite a big part of the problem. I'm not sure what "longstanding unresolved downright-existential bugs" prevent anyone from doing that, and if these bugs are "downright existential" then how has the site survived for six more years since the above comment?

**Comment by benkasminbullock** [comment]
I've added the viewport here: https://github.com/blogs-perl-org/blogs.perl.org/pull/406

**Comment by ap** [comment]
I’ve added a basic stylesheet to make the site mobile-friendly now.

The new stylesheet is not applied on all blogs just yet because that would require a full site rebuild and I want to hold off on that until after a few more changes. But it can be seen on the front page, the Meta blog and on mine. (Also, any user who rebuilds their blog individually will also get the changes so far applied on their blog.)
