### ISSUE TITLE
No SSL????

### ISSUE THREAD

**Issue by FGasper** [blogs-perl-org/blogs.perl.org#323]
Why is there no SSL on this blog???

I’m more than happy to help that get set up; the module I’d like to blog about, Net::ACME, would make that quite simple.

**Comment by davorg** [comment]
Because no-one has been brave enough to wade into the Movable Type installation in order to set it up.

And given that we're getting closer to [moving the whole site](http://news.perlfoundation.org/2016/11/public-beta-of-blogsperlorg-re.html) over to a completely new technology, I doubt that there's any enthusiasm for doing it now.

**Comment by FGasper** [comment]
No SSL on the beta, either … ?

**Comment by davorg** [comment]
Feel free to report that to the people working on the replacement - https://pearlbee.uservoice.com/

**Comment by FGasper** [comment]
Done. Thanks!

**Comment by cxw42** [comment]
@ap @davorg As far as I can tell, the switchover hasn't happened yet.  (Am I missing something?)  Given that, and since LetsEncrypt is now an option, woud you be willing to revisit this?  Thanks for considering this request!
