### ISSUE TITLE
Login or reset password

### ISSUE THREAD

**Issue by byterock** [blogs-perl-org/blogs.perl.org#324]
Can't seem to login or change password.  

Happened yesterday

**Comment by arc** [comment]
Sorry about that. On Friday, we saw another example of something that happens from time to time: an extended attack wherein a single spammer registers a series of new user accounts, posting spam from each account as fast as we can disable the accounts and clean up the mess. When that happens, the only tool Movable Type gives us to deal with the problem is to close down registrations temporarily. However, there seems to be a Movable Type bug that prevents various sorts of user action (including logging in!) while registrations are disabled.

We know that this is extremely painful for our users, and I do apologise for it. I'm glad to say that the replacement blogs.perl.org platform is [currently in beta](http://news.perlfoundation.org/2016/11/public-beta-of-blogsperlorg-re.html), so hopefully all these Movable Type problems will soon be a thing of the past.

In the meantime, I've reenabled user registrations, which I believe will have restored your ability to log in (at least until we get another spam attack of this sort).

Thanks for your patience.
