### ISSUE TITLE
Can't find markdown docs

### ISSUE THREAD

**Issue by matthewpersico** [blogs-perl-org/blogs.perl.org#325]
Cannot seem to find how to make a highlighted perl code block, See 'http://blogs.perl.org/users/matthew_persico/2016/12/saving-breakpoints-in-the-perl-debugger.html'. How do I make perl code blocks? Thanks

**Comment by ap** [comment]
Since b.p.o uses the original Markdown plugin by John Gruber, you can refer to [his Markdown syntax description](https://daringfireball.net/projects/markdown/syntax#precode): either indent the code, or just use `<pre><code>…</code></pre>` directly (in which case you can also put links, use strong/emphasis, underlines, etc).

**Comment by matthewpersico** [comment]
Thank you. I indented the code by 4 spaces, but that did not seem to work. However, the <pre><code> sequence works just fine.
