### ISSUE TITLE
Bug on in blogs.perl.org

### ISSUE THREAD

**Issue by dalvia62** [blogs-perl-org/blogs.perl.org#338]
During my testing I noticed that perl website http://blogs.perl.org seems to leak some data into internet. Username directory http://blogs.perl.org/users/ is showing files which I suppose shouldn't be visible to internet.

I noticed that these files include username list  on your website ( including every user username with his Activity date & time  ),

Just open URL http://blogs.perl.org/users/ and start seeing the list of username with with his active time and date 

i have test this bug and this bug is valid bug

for example

i create a account right now with the username test123
just checkout my link http://blogs.perl.org/users/test123/

and then i saw that username coming in list of directory

so this is very harmful because any one can find your user detail and also find Activity date and time 

checkout attach file

User Detail 

User Activity Date

User Activity Time 

Thank you 

from
Ro
![screenshot 175](https://cloud.githubusercontent.com/assets/12573917/26000455/ab799de0-3746-11e7-8466-78e900ee797a.png)
hit Dalvi

Hacker101

**Comment by arc** [comment]
Sorry, this isn't a bug: it is completely desirable that people who've signed up for an account on a public blogging system will appear in a list of such people. There is no unexpected information disclosure here.

**Comment by ap** [comment]
Strictly speaking those are blog names, not user names, although in our case they are set up the same. And I’m pretty sure the timestamp is (at most) the time of when that blog was last rebuilt, i.e. roughly the last time something was posted on it publicly.

So for blogs that have already posted an article publicly, there isn’t a single piece of information in the directory listing that isn’t otherwise already disclosed by the very act of posting. There *is* a very limited level of disclosure about blogs where nothing has been publicly posted yet: namely their name and time of creation.

I don’t consider that level of disclosure a problem.
