### ISSUE TITLE
Increase # articles on main page?

### ISSUE THREAD

**Issue by djzort** [blogs-perl-org/blogs.perl.org#339]
I suggest that the number of articles on the front page be doubled.

There are a lot of articles being posted regularly (which is a good thing), alas this means that articles are being pushed down and off the front page very quickly. Increasing the number would provide a simple solution and increase exposure for peoples content.

By contemporary standards, the page is not that big (in terms of kb) - so dont see load times as being dramatically impacted even on mobile devices.

**Comment by arc** [comment]
@davorg @ap I'd be OK with this — 20 articles per page instead of 8, say. Any thoughts?

**Comment by davorg** [comment]
I'd be happy with that too.

**Comment by ap** [comment]
Sure.

@arc: you foot the bill, so it’s up to you… because as far as I care, make it 200. The front page is 24kb, could easily be bumped to 200kb I think. I’m inclined to be as generous as reasonable UX and resource constraints will permit.

I suppose I might have made noises about this if I ever actually used the front page myself (rather than RSS), because yeah, 8 is a rather low limit.

I guess that makes more sense when the page is dynamically generated – and we do fall back to dynamic generation after the first few pages, right? So possibly bump the dynamic pagination to slightly more than 8 and then bump the statically generated pages to some multiple of that (to make sure the switch-over point is always on a boundary)?

**Comment by arc** [comment]
The bandwidth isn't an issue: we're only using a tiny fraction of our tens-of-terabytes-per-month transfer limit anyway. And the files are all statically generated, so there's nothing complicated that needs to be done.

I'll just bump the count right now. If we want to tweak it again later, that'll be easy too.

**Comment by djzort** [comment]
good outcome.
