### ISSUE TITLE
Can't register an account

### ISSUE THREAD

**Issue by masak** [blogs-perl-org/blogs.perl.org#52]
I'm running Chrome 4.0.249.30 on Mac OS X 10.6.2.

Trying to sign up on http://blogs.perl.org/mt/mt-cp.fcgi , I'm getting "Text entered was wrong. Try again."

As far as I'm concerned, that shouldn't even be an error message. The application may as well say "I don't feel like it." That helps me figure out what to do differently about as much as "Text entered was wrong" does.

I have an "ä" in my last name, but I've tried signing up writing "Masak" instead, and that doesn't work either. For what it's worth, the username I tried to register is "masak".

**Comment by ap** [comment]
This is a very old issue, there’s been several bugfixes related to this error in various places since, and people have been signing up successfully for a long time. I generally hate to close issues without positive evidence of resolution, but if I leave this open it will just sit around forever fruitlessly, so I’ll just assume that if there still is a related problem, another issue will be filed.
